name: Terraform Module Test with Go

on:
  push:
    branches:
      - main

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      TF_LOG: DEBUG # Terraform 디버그 로그 활성화
      TF_LOG_PATH: ./terraform-debug.log # 로그를 파일로 저장

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3
        terraform_wrapper: false

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Initialize Go Module
      run: |
        cd test
        go mod init github.com/test/db-module
        go mod tidy

    - name: Run Terraform Tests
      working-directory: ./test
      run: go test -v

    - name: Upload Terraform Debug Log
      uses: actions/upload-artifact@v3
      with:
        name: terraform-debug-log
        path: ./terraform-debug.log